---
- hosts: all
  become: yes
  tasks:
    - name: Ensure NTP is installed.
      yum: name=ntp state=present

    - shell: |
        if ! rpm -qa | grep -qw ntp; then
          yum install -y ntp
        fi

    - name: Ensure NTP is running.
      service: name=ntpd state=started enabled=yes