---
# Playbook to install httpd and other files.
- name: Install Apache.
  hosts: all
  become: true

  tasks:
    - name: Install Apache.
      yum: 
        name:
          - httpd
          - httpd-devel
        state: present

    - name: Copy config files.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: httpd.conf
          dest: /etc/httpd/conf/httpd.conf
        - src: httpd-vhosts.conf
          dest: /etc/httpd/conf/httpd-vhosts.conf

    - name: Ensure Apache is started and configured to run on boot.
      service:
        name: httpd
        state: started
        enabled: true
